name: main
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      repo: btwrk/action-jira-linter-test
      branch_name: feature/dx-1905_${{ github.sha }}
      GH_TOKEN: ${{ secrets.GH_JIRA_TEST_TOKEN }}
    steps:
      - name: checkout jira-linter-test
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo }}
          ref: main
          token: ${{ env.GH_TOKEN }}
      - name: configure git
        run: |
          git config --global user.email "jira-linter@example.com"
          git config --global user.name "jira-linter"
      - name: create branch
        run: git checkout -b "${branch_name}"
      - name: rename workflow
        run: |
          sed -i.bak 's/name: jira-linter/name: jira-linter-${{ github.sha }}/' .github/workflows/jira-linter.yml
      - name: commit content
        run: git commit -am "Renamed workflow to jira-linter-${{ github.sha }}"
      - name: push
        run: git push --set-upstream origin "${branch_name}"
      - name: create pull request
        run: gh pr create --title "Test for GitHub Actions" --body " "
      - name: list runs
        run: gh run list --repo "${repo}"
      - name: watch runs
        run:  gh run list --repo "${repo}" --json databaseId --jq .[].databaseId | while read id; do gh run watch "${id}" --exit-status --repo "${repo}"; done;
      - name: cleanup
        run: git push origin --delete "${branch_name}"
