name: main
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      branch_name: feature/dx-1905_${{ github.ref }}
      GH_TOKEN: ${{ secrets.GH_JIRA_TEST_TOKEN }}
    steps:
      - name: checkout jira-linter-test
        uses: actions/checkout@v3
        with:
          repository: btwrk/jira-linter-test
          ref: main
          token: ${{ env.GH_TOKEN }}
      - name: configure git
        run: |
          git config --global user.email "jira-linter@example.com"
          git config --global user.name "jira-linter"
      - name: create branch
        run: git checkout -b "${branch_name}"
      - name: create content
        run: echo "${{ github.ref }}" >> README.md
      - name: commit content
        run: git commit -am "Added ${{ github.ref }}"
      - name: push
        run: git push --set-upstream origin "${branch_name}"
      - name: create pull request
        run: gh pr create --title "Test" --body " "
